<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Groupcat\Block\Framework\Pricing\HideAddTo $block */
/** @var string $productIdName */
/** @var string $jsonData */
?>

<span id="<?= $block->escapeHtml($productIdName) ?>" style="display: none !important;"></span>
<script>
    require([
        "jquery",
        "Amasty_Groupcat/js/amHideAddTo"
    ], function ($, amHideAddTo) {
        $( document ).ready(function() {
            $("#<?= $block->escapeHtml($productIdName) ?>").amHideAddTo(<?= /** @noEscape */ $jsonData ?>);
        });
    });
</script>
