<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Customer Group Catalog for Magento 2
*/
?>
<?php
/** @var \Amasty\Groupcat\Block\Framework\Pricing\HideAddTo $block */
/** @var string $productIdName */
/** @var string $jsonData */
?>

<span id="<?= $block->escapeHtml($productIdName) ?>" style="display: none !important;"></span>
<script>
    require([
        "jquery",
        "Amasty_Groupcat/js/amHideAddTo"
    ], function ($, amHideAddTo) {
        $( document ).ready(function() {
            $("#<?= $block->escapeHtml($productIdName) ?>").amHideAddTo(<?= /** @noEscape */ $jsonData ?>);
        });
    });
</script>
