<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Customer Group Catalog for Magento 2
*/
?>
<?php
/** @var \Magento\Backend\Block\Template $block */
?>
<div class="admin__field-tooltip amgroupcat-tooltip">
    <a class="admin__field-tooltip-action action-help"
       target="_blank"
       title="<?= $block->escapeHtml(__('You can not find the required attribute in product conditions?')); ?>"
       tabindex="1"
       data-bind="attr: {href: tooltip.link}">
    </a>
    <div class="admin__field-tooltip-content amgroupcat-image" data-bind="html: tooltip.description">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Amasty_Groupcat::images/groupcat-1.gif')); ?>"
             alt="<?= $block->escapeHtml(__('How to find required attribute')); ?>">
    </div>
</div>
