<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "amreindex-status-checker": {
                            "component": "Amasty_Reindex/js/status-checker",
                            "url": "<?= $block->escapeUrl($block->getUrl('amreindex/reindex/status')); ?>"
                        }
                    }
                }
            }
        }
</script>
