<?php
/**
 * @var Tigren\Kojs\Block\Account $block ;
 */
?>
<div id="custom-component" data-bind="scope:'customcomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
         "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "Tigren_Kojs/js/view/test",
                        "config": {
                            "template": "Tigren_Kojs/knockout-test",
                            "provider": "othercase-test"
                        }
                    }
                }
            }
        }
    }


    </script>
</div>
<div id="other-component" data-bind="scope: 'othercase-test'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#other-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "othercase-test": {
                        "component": "Tigren_Kojs/js/view/product",
                        "config": {
                            "template": "Tigren_Kojs/product-test",
                            "provider": "customcomponent"
                        }
                    }
                }
            }
        }
    }



    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function (url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        });
    </script>
</div>
