<?php
/*
 * @autdor    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * @var ListBook $block ;
 */

use Tigren\BookStore\Block\ListBook;

$data = $block->getAllBooks();
?>
<div class="form_container">
    <table class="book_table" border="1">
        <tr>
            <th>Entity ID</th>
            <th>Title</th>
            <th>Pages</th>
            <th>Author ID</th>
            <th>Author</th>
            <th>Age</th>
            <th>Gender</th>
        </tr>
        <?php foreach ($data as $item):
            ?>
            <tr>
                <td><?= $item['entity_id'] ?></td>
                <td><?= $item['title'] ?></td>
                <td><?= $item['page'] ?></td>
                <td><?= $item['author_id'] ?></td>
                <td><?= $item['name'] ?></td>
                <td><?= $item['age'] ?></td>
                <td><?= $item['gender'] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
