<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * @var Tigren\Question\Block\Edit $block
 */
$getQuestion = $block->getQuestion();
?>

<head>
    <title>Form Edit Question</title>
</head>

<div id="custom_form">
    <form class="form form-edit-account"
          enctype="multipart/form-data"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          autocomplete="off">
        <button class="action submit primary"><a style="color: white" href="<?= $block->getUrl('*/*/listquestion') ?>">
                <?php echo __('View All Questions') ?></a></button>
        <fieldset class="fieldset info">
            <legend style="text-align: center; font-size: 25px; font-family: monospace; color: #0a820b" class="legend">
                <b><span><?= $block->escapeHtml(__('Edit Question')) ?></span></b></legend>
            <input name="id" id="id" title="<?php echo __('ID') ?>" class="input-text" type="hidden"
                   value="<?= $getQuestion->getEntityId() ?>"/>
            <div class="field title required">
                <label class="label" for="title"><span><?php echo __('Title') ?></span></label>
                <div class="control">
                    <input name="title" id="title" title="<?php echo __('Title') ?>" class="input-text" type="text"
                           value="<?= $getQuestion['title'] ?>"/>
                </div>
            </div>
            <div class="field content required">
                <label class="label" for="title"><span><?php echo __('Content') ?></span></label>
                <div class="control">
                    <textarea name="content" id="content" title="<?php echo __('Content') ?>"
                              class="input-text"> <?= $getQuestion['content'] ?> </textarea>
                </div>
            </div>
            <button type="submit" title="<?php echo __('Submit') ?>"
                    data-question-id="<?= $getQuestion->getEntityId() ?>" class="action submit primary"
                    id="submit_form_btn">
                <span><?php echo __('Submit') ?></span>
            </button>
        </fieldset>
    </form>
</div>

<script>
    require(
        [
            'jquery',
            'mage/translate',
            'mage/storage',
            'ko',
            'Tigren_Question/js/model/url-builder'
        ], function (
            $,
            $t,
            storage,
            ko,
            urlBuilder
        ) {
            $('#submit_form_btn').on('click', function (event) {
                var title = $('#title').val();
                var content = $('#content').val();
                var id = $('#id').val();
                if (title && content) {
                    event.preventDefault();
                    storage.post(
                        urlBuilder.createUrl('/tigren_question/update/', {}),
                        JSON.stringify({
                            id: id,
                            title: title,
                            content: content,
                        }),
                    ).done(function (data) {
                            if (data === true) {
                                console.log(data);
                                alert('Upadte Question Successfully!!!');
                                window.location.href = '/question/create/listquestion'
                            }
                        }
                    ).fail(
                        function (response) {
                        }
                    );
                }
            });
        })

</script>