<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * @var Tigren\Question\Block\Edit $block
 */
$getQuestion = $block->getQuestion();
?>

<head>
    <title>Form Edit Question</title>
</head>

<div id="custom_form">
    <form class="form form-edit-account"
          action="<?= $block->escapeUrl($block->getUrl("*/*/update")) ?>.?id=<?= $getQuestion['entity_id'] ?>"
          method="post"
          id="custom_form"
          enctype="multipart/form-data"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          autocomplete="off">
        <button><a href="<?= $block->getUrl('*/*/listquestion') ?>">View All Question(s)</a></button>
        <fieldset class="fieldset info">
            <legend class="legend"><span><?= $block->escapeHtml(__('Edit Question Form')) ?></span></legend>
            <div class="field title required">
                <label class="label" for="title"><span><?php echo __('Title') ?></span></label>
                <div class="control">
                    <input name="title" id="title" title="<?php echo __('Title') ?>" class="input-text" type="text"
                           value="<?= $getQuestion['title'] ?>"/>
                </div>
            </div>
            <div class="field content required">
                <label class="label" for="title"><span><?php echo __('Content') ?></span></label>
                <div class="control">
                    <input name="content" id="content" title="<?php echo __('Content') ?>" class="input-text"
                           type="text"
                           value="<?= $getQuestion['content'] ?>"/>
                </div>
            </div>
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                <span><?php echo __('Submit') ?></span>
            </button>
        </fieldset>
    </form>
</div>