<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * @var Tigren\Question\Helper\Data $helper
 */
$helper = $this->helper(Tigren\Question\Helper\Data::class);
$question = $helper->getListQues();
if ($question->count()) {
    ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('ID') ?></th>
                <th scope="col" class="col name"><?php echo __('Title') ?></th>
                <th scope="col" class="col email"><?php echo __('Content') ?></th>
                <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
                <th scope="col" class="col author_id"><?php echo __('Author ID') ?></th>
                <th scope="col" colspan="2" class="col actions"><?php echo __('Actions') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($question as $item): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                        <?php echo $item['entity_id'] ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Title')) ?>" class="col title">
                        <?php echo $item['title'] ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Content')) ?>" class="col content">
                        <?php echo $item['content'] ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                        class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Author ID')) ?>" class="col author id">
                        <?php echo $item['author_id'] ?></td>
                    <td>
                        <button><a href="<?= $block->getUrl("*/*/edit") ?>?id=<?= $item['entity_id'] ?>" )>Edit</a>
                        </button>
                        <button><a href="<?= $block->getUrl("*/*/delete") ?>?id=<?= $item['entity_id'] ?>" )
                                   onclick="return confirm('Do you want delete the question ?')">Delete</a></button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php
}
?>
<form action="<?= $this->getUrl('question/create/index') ?>">
    <button type="submit" title="<?php echo __('Create Question') ?>"
            class="action submit primary" id="custom_btn">
        <span><?php echo __('Create Question') ?></span>
</form>