<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Customer Group Catalog for Magento 2
*/
?>
<?php
/** @var \Amasty\Groupcat\Block\Framework\Pricing\RequestPopup $block */
?>
<a href="<?= (int)$block->getLink() ?>" class="amasty-hide-price-container" <?= /* @noEscape */ $block->getCustomStyles() ?>>
    <?= /* @noEscape */ $block->getContent(); ?>
</a>