<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Groupcat\Block\Framework\Pricing\RequestPopup $block */
?>
<a href="<?= (int)$block->getLink() ?>" class="amasty-hide-price-container" <?= /* @noEscape */ $block->getCustomStyles() ?>>
    <?= /* @noEscape */ $block->getContent(); ?>
</a>