<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Groupcat\Block\Framework\Pricing\RequestPopup $block */
/** @var \Magento\Catalog\Api\Data\ProductInterface $product */
/** @var string $formConfig */
?>

<a data-product-id="<?= (int)$product->getId() ?>" data-amhide="AmastyHidePricePopup" class="amasty-hide-price-container" <?= /* @noEscape */ $block->getCustomStyles() ?> >
    <?= /* @noEscape */ $block->getContent(); ?>
</a>

<script type="text/x-magento-init">
    {
        "*": {
            "Amasty_Groupcat/js/amHidePriceForm": <?= /* @noEscape */ $formConfig ?>
        }
    }
</script>