<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

$item = $this->helper(Tigren\CustomerGroupCatalog\Helper\Data::class)->getRules();
$discount = $this->helper(Tigren\CustomerGroupCatalog\Helper\Data::class)->getDiscount();
?>
<style>
    td {
        text-align: center;
    }

    #center {
        text-align: center;
    }
</style>

<button class="action submit primary"><a style="color: white" href="<?= $block->getUrl('') ?>">
        <?php echo __('Go to Homepage :D') ?></a></button>
<div>
    <p style="color: rebeccapurple; font-weight: bold; font-size: 18px" id="center">
        Congratulation!!! You have received discount <?= $discount * 100 ?> % with several products!!!
    </p>
</div>
<br><br>
<div style="text-align: center; color: #0a820b; font-family: monospace; font-size: 25px;">
    <b>Rule Infomation</b></div>
<hr>
<table border="1">
    <tr>
        <th id="center">Rule ID</th>
        <th id="center">Name</th>
        <th id="center">Products applied</th>
        <th id="center">Customer Group View</th>
        <th id="center">Discount Amount (%)</th>
        <th id="center">Priority</th>
    </tr>

    <tr>
        <td><?= $item['rule_id'] ?></td>
        <td><?= $item['name'] ?></td>
        <td><?= $item['products'] ?></td>
        <td><?= $item['customer_group_ids'] ?></td>
        <td><?= $item['discount_amount'] ?></td>
        <td><?= $item['priority'] ?></td>
    </tr>

</table>

