<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Customer Group Catalog for Magento 2
*/
?>
<?php
/** @var \Amasty\Groupcat\Block\Framework\Pricing\Request\Content $block */
$url = $block->getImageUrl();
$text = $block->getText();
?>
<?php if ($url): ?>
    <img class="amasty-hide-price-image" src="<?= $block->escapeUrl($url) ?>"/>
<?php endif; ?>

<?php if ($text): ?>
    <span class="amasty-hide-price-text"><?= $block->escapeHtml($text) ?></span>
<?php endif; ?>
