<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Groupcat\Block\Framework\Pricing\Request\Content $block */
$url = $block->getImageUrl();
$text = $block->getText();
?>
<?php if ($url): ?>
    <img class="amasty-hide-price-image" src="<?= $block->escapeUrl($url) ?>"/>
<?php endif; ?>

<?php if ($text): ?>
    <span class="amasty-hide-price-text"><?= $block->escapeHtml($text) ?></span>
<?php endif; ?>
